name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Destroy AWS EC2'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ID_ACCESS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
      AWS_REGION: eu-west-1  # optional but recommended

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.12.1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -target=aws_instance.Terraform_EC2

    - name: Terraform Destroy
      run: terraform destroy -target=aws_instance.Terraform_EC2 -auto-approve